### ISSUE TITLE
Serialization of RBFInterpolant objects

### ISSUE THREAD

**Issue by iraikov** [treverhines/RBF#2]
Hello,

It is sometimes useful to serialize RBFInterpolant objects and send them across the network or save and restore them from file. However, the usual pickle machinery complains that it cannot handle the '_basis' field of RBFInterpolant because it is a function. One solution is to allow passing of basis function coefficients to the RBFInterpolant constructor, so that interpolant objects can be quickly reconstituted after serializing their _y and _coeff fields. I would appreciate any solution to this problem.

**Comment by treverhines** [comment]
Hi Ivan,

The easiest solution is to store the name of the function rather than the function itself for the `_basis` attribute. I made a new branch for this issue, and the `RBFInterpolant` in that branch should be picklable if you instantiate it with a string for the `basis` argument. The string should be the name of the function from the `rbf.basis` module. For example,
```
picklable_instance = RBFInterpolant(y,d,basis='phs3')
```   
This is a hackish patch, and I will come up with a better solution when I have some free time. Let me know if this solves your problem.

**Comment by iraikov** [comment]
Hi Trever,
Thank you very much for your response and your suggestion. I should have mentioned that this issue was actually motivated by my use of RBF in MPI codes where each process instantiates an interpolant. The problem is that when there are too many processes on a node, the memory is exhausted when all processes attempt to compute the interpolation coefficients. Hence my idea was to have just one process compute the coefficients and send them to all others. Let me combine your idea with an extra coeffs argument to the constructor and see if I can work it out.

**Comment by iraikov** [comment]
Hi Trever,
I have been using this feature for a few months now, using the serialization branch and my modification to provide the coeffs argument to the constructor of RBFInterpolant. Would it be possible to merge these changes, or have you had further thoughts on the subject? Thank you very much!

**Comment by treverhines** [comment]
Hi Ivan. RBFInterpolant in master is now picklable regardless of how it was initialized. So you can specify the basis functions as either a string or an RBF instance and it should be picklable.

**Comment by iraikov** [comment]
Hi Trever, this is great news! Thank you for your work.
