### ISSUE TITLE
Release pip-installable version

### ISSUE THREAD

**Issue by frthjf** [treverhines/RBF#26]
Thanks for this package! I am wondering if you'd be willing to release it to `pip` so it can be installed via `pip install rbf` or similar? I'd be happy to prepare a PR with the necessary setup. 

Related #14

**Comment by gircobain** [comment]
Up
Any news on this?

**Comment by frthjf** [comment]
Not exactly a pip package, but for what it's worth, I ended up creating PEP 518 compliant fork. Feel free to check it out.

```toml
rbf = {git = "https://github.com/frthjf/RBF.git", rev = "master"}
```

**Comment by treverhines** [comment]
I just put this package up on pypi here https://pypi.org/project/treverhines-rbf/

Can you try installing with `pip install treverhines-rbf`? You may have to delete existing installations because I changed the package name and I am not sure if that will create conflicts. You should see `rbf.__version__` is 2024.1.7.

**Comment by frthjf** [comment]
Thanks! From a quick look, it seems to install fine 👍
