### ISSUE TITLE
Citing this Repository in my work!

### ISSUE THREAD

**Issue by lalit-pathak** [treverhines/RBF#27]
Could somebody please tell me how to cite this repository? I am a PhD student and have used this repository in my work. I have found that GitHub has added support for direct citations but couldn't figure out how to do it for this repository.

Thanks

**Comment by treverhines** [comment]
Thanks for asking! There is no paper describing this repo, so you would just cite it however you would cite other software.  Perhaps something like

> Hines, T. (2015). RBF. https://github.com/treverhines/RBF

Here is an example of a paper that cited this repo 
 https://arxiv.org/pdf/1912.13282.pdf
 
 It looks like I need to add a `CITATION.cff` file to this repo so that github will show you how to cite it.
